### ISSUE TITLE
implement frontend template

### ISSUE THREAD

**Issue by TuranC** [VilnaCRM-Org/website#1]
As a customer i want to be able to read about VilnaCRM and register on it.

Landing design: https://www.figma.com/file/hubQLvQkAlz8wWs2C60T3p/VilnaCRM?node-id=19%3A965

### Technical requirements

- [x] Typescript
- [x] React
- [x] MUI
- [x] Husky
- [x] Jest
- [x] Cypress
- [x] Storybook
- [x] Pnpm
- [x] ESlint
- [x] ReactDOMServer vs/with Next.js
- [ ] [MSW](https://mswjs.io/)
- [x] Appolo GraphQL
- [x] router (next.js)
- [x] sentry (https://www.npmjs.com/package/@sentry/node)
- [x] react testing library (https://testing-library.com/docs/react-testing-library/intro)
- [ ] turbopack (https://turbo.build/pack)

### Tasks

- [ ] init ui repository for Website and CRM with UI components
- [ ] init template repository regarding to [best practices](https://github.com/alan2207/bulletproof-react)
- [ ] init website repository from the template repository
- [ ] write website design in the [document](https://miro.com/app/board/uXjVPRE64mI=/?share_link_id=214380289179) following the [C4 model](https://c4model.com/)
- [ ] set up docker for service
- [ ] set up CI checks using Github actions (**eslint**, jslint, deepscan, security testing (SYNK (SAST), OWASP ZAP (DAST)), load testing (jmeter) (https://dev.to/hiroyone/frontend-testing-no-more-unitintegratione2e-categorizations-and-priorities-5358), perfomance testing (lighthouse), [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) and etc.)
- [ ] write for all repositories CONTRIBUTE.md and README.md
- [ ] add [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- [ ] develop SSR website following the design 
- [ ] implement Storybook page for ui, website repositories
- [ ] cover the code with auto-tests
- [ ] Image optimization CI check (https://github.com/marketplace/actions/image-actions)

### Subtasks

- [x] check if it is possible to check lighthouse data and if it is less than the given number then it should fall
- [x]  write a cypress and unit test to create a git action for e2e and unit
- [x] create github actions names based on test names (https://dev.to/hiroyone/frontend-testing-no-more-unitintegratione2e-categorizations-and-priorities-5358)
- [ ] connect sonarqube
- [ ] look for IAST tool and see if it can be used it our project
- [x] add artillery for load testing
- [ ] research the question of how to make your own route in ssr
- [ ] add [i18n](https://www.npmjs.com/package/react-i18next) (internationalization)
- [x] check lighthouse for mobile version (ci check)
- [x] update node to last version
- [ ] add memlab to CI check (https://github.com/facebook/memlab)
- [x] add jsdoc
- [x] add [codesence](https://codescene.com/)
- [ ] add [web-vitals](https://www.npmjs.com/package/web-vitals) 

### Optional

- [ ] add https://github.com/artilleryio/artillery-engine-playwright

### Acceptance criteria

- [ ] website exists and corresponds to design
- [ ] CI works when developer create a PR
- [ ] all tests passed
