### ISSUE TITLE
make layout website

### ISSUE THREAD

**Issue by TuranC** [VilnaCRM-Org/website#3]
As a customer i want to be able to see vilnaCRM website

this task for main website page

[design](https://www.figma.com/file/hubQLvQkAlz8wWs2C60T3p/VilnaCRM?node-id=19%3A965&t=lwGTlaRoEmN3HPo5-0)

### Technical requirements

- [ ] react (https://reactjs.org/)
- [ ] nextjs (https://nextjs.org/)
- [ ] nextjs routes (https://nextjs.org/docs/routing/introduction)
- [ ] typescript (https://www.typescriptlang.org/)
- [ ] MUI (https://mui.com/)
- [ ] Cypress (https://www.cypress.io/)
- [ ] jest (https://jestjs.io/ru/)
- [ ] react testing library (https://testing-library.com/docs/react-testing-library/intro)
- [ ] Storybook (https://storybook.js.org/)

### Tasks

- [ ] implement the sticky menu, add the supporting to responsive design for [statcounter](https://gs.statcounter.com/screen-resolution-stats), button "try it out" must scroll to the section with registration which must be at the bottom
  - [ ] for mobile version menu must open like drop-down list
- [ ] use for all texts i18n (for example `t('text_1')`) [react-i18next](https://github.com/i18next/react-i18next#what-will-my-code-look-like)
- [ ] implement header, add block header according to design
- [ ] implement block "why we", add [slider](https://mui.com/material-ui/react-stepper/#text-with-carousel-effect) for mobile
- [ ] implement block "for who", add button "try it out"
- [ ] implement block "unlimited possibilities of integrations", add a slider for the mobile version
- [ ] implement registration block
  - [ ] add a registration form
  - [ ] add validation for form (initial, password, email)
  - [ ] add registration button and add mock for registration
  - [ ] add the possibility of registration for a google account, GitHub, Facebook, or Twitter
- [ ] implement footer
  - [ ] icons after click must open our Instagram. facebook, GitHub, LinkedIn
  - [ ] email must have [mailto](https://css-tricks.com/snippets/html/mailto-links/) links
- [ ] add e2e tests
  - [ ] if set mobile width and click menu, must open menu and be visible
  - [ ] if click "try it out" website must scroll to the bottom where registration block
  - [ ] check registration inputs, they must validate data in input
  - [ ] 
- [ ] add unit tests

### acceptance criteria 

- [ ] pixel perfect
- [ ] all website according to design
- [ ] all website have responsive design
- [ ] self review
